### ISSUE TITLE
Suggestion for readme

### ISSUE THREAD

**Issue by stuartcampbell** [caley/OpenEPSim#1]
Hi, I am currently reviewing your submission for JOSS (https://github.com/openjournals/joss-reviews/issues/650) and had a small suggestion for your readme file.  After you get the output, you show some plots.  It would be nice to give the user a pointer or code, or hints on how to go about plotting the output.  
Thank you 
Stuart

**Comment by caley** [comment]
Hi Stuart,

I've added some sample code to produce plots like those in the readme.  The code uses Python, because it's simpler to produce quick plots than with Java.

Cheers,

Caley

**Comment by stuartcampbell** [comment]
Excellent - Thank you.  Looks good.
