### ISSUE TITLE
Expand CI use

### ISSUE THREAD

**Issue by stuartcampbell** [caley/OpenEPSim#2]
Hi, It looks like you have an initial travis.yml file.  It would be nice if this was fleshed out to run the compile and tests (which worked beautifully).  

Cheers
Stu 

Link to the JOSS review: https://github.com/openjournals/joss-reviews/issues/650

**Comment by caley** [comment]
Hi Stu,

Travis CI is already compiling the project and running the tests.  I've added a build status badge to the readme to link to this.  Were you suggesting any more than this?

Cheers,

Caley

**Comment by stuartcampbell** [comment]
Yeah this is great.  I forgot that travis picks up the `pom.xml` file automagically - and I couldn't find a successful build on travis.  But the badge helps find it.
